name: Prefect Cloud Deployment

env:
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

on:
  pull_request:
    branches: [ "main" ] 
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-flow-load:
    name: Build and apply prefect deployment

    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          sparse-checkout: src

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements*.txt"
      
      - name: Install Prefect
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r requirements-prefect.txt
  
      - name: Build and apply deployment
        run: |
          prefect deployment build ./src/basic_flow.py:basic_flow \
            --name "Demo basic flow" \
            --storage-block github/youtube-data \
            --tag github \
            --work-queue githubwq \
            --version $GITHUB_SHA \
            --apply 
