# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Python Code Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Python Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout: src

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black mypy 
      
      - name: Critical Checks 
        run: |
          black --check src/*
          mypy --ignore-missing-imports --explicit-package-bases --implicit-optional src/*
