# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Python Code Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and check python files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout: src
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements*.txt"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r requirements-python.txt
      
      - name: Critical Checks 
        run: |
          black . --check
          mypy . --ignore-missing-imports --explicit-package-bases --implicit-optional

      - name: Linting Checks
        run: |
          flake8 . --count --ignore=E501,W503 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Test Checks
        run: |
          pytest
